#!/bin/sh
# nen installer — https://github.com/rlaope/nen
#
#   curl -fsSL https://raw.githubusercontent.com/rlaope/nen/main/install.sh | sh
#   curl -fsSL https://raw.githubusercontent.com/rlaope/nen/main/install.sh | sh -s -- --agent cursor
#
# Installs the six nen skills for the agent you use. Skill bodies always land
# in $NEN_HOME (default ~/.nen) as plain SKILL.md files; per-agent wiring is a
# thin layer on top, so every runtime reads the same skill text.
set -eu

REPO_TARBALL="https://codeload.github.com/rlaope/nen/tar.gz/refs/heads/main"
NEN_HOME="${NEN_HOME:-$HOME/.nen}"
SKILLS="enhancer transmuter emitter specialist conjurer manipulator"
AGENT="auto"
DEST=""

usage() {
  cat <<'EOF'
nen installer

  --agent <name>   claude | cursor | codex | opencode | gemini | qwen |
                   kimi | antigravity | pi | copilot | agents-md | auto (default)
  --dest <path>    override the instructions-file path (agents-md family only)
  --help           this text

Targets:
  claude       copy the repo to ~/.claude/skills/nen (loads namespaced as nen@skills-dir)
  cursor       generate .cursor/rules/nen-<skill>.mdc in the current project
  copilot      append the routing block to .github/copilot-instructions.md
  codex        routing block in ~/.codex/AGENTS.md
  opencode     routing block in ~/.config/opencode/AGENTS.md
  gemini       routing block in ~/.gemini/GEMINI.md
  qwen         routing block in ~/.qwen/QWEN.md
  kimi | antigravity | pi | agents-md
               routing block in ./AGENTS.md (the cross-agent convention)
  auto         detect installed agents and install for each one found

The routing block is small on purpose: it carries only each skill's trigger
description plus the rule "read the SKILL.md before acting" — full bodies load
on demand from ~/.nen/skills/<name>/SKILL.md.
EOF
}

while [ $# -gt 0 ]; do
  case "$1" in
    --agent) AGENT="$2"; shift 2 ;;
    --dest) DEST="$2"; shift 2 ;;
    --help|-h) usage; exit 0 ;;
    *) echo "unknown option: $1" >&2; usage; exit 1 ;;
  esac
done

say() { printf '%s\n' "$*"; }

fetch_repo() {
  WORK="$(mktemp -d)"
  trap 'rm -rf "$WORK"' EXIT
  say "Fetching nen..."
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL "$REPO_TARBALL" | tar -xz -C "$WORK"
  elif command -v git >/dev/null 2>&1; then
    git clone --depth 1 --quiet https://github.com/rlaope/nen.git "$WORK/nen-main"
  else
    echo "need curl or git" >&2; exit 1
  fi
  SRC="$WORK/nen-main"
  [ -d "$SRC/skills" ] || { echo "download looks wrong: no skills/ in $SRC" >&2; exit 1; }
}

install_home() {
  mkdir -p "$NEN_HOME/skills"
  for s in $SKILLS; do
    mkdir -p "$NEN_HOME/skills/$s"
    cp "$SRC/skills/$s/SKILL.md" "$NEN_HOME/skills/$s/SKILL.md"
  done
  say "Skill bodies installed to $NEN_HOME/skills"
}

skill_description() {
  # frontmatter description line of one skill, without the leading key
  sed -n 's/^description: //p' "$NEN_HOME/skills/$1/SKILL.md" | head -1
}

routing_block() {
  cat <<EOF
<!-- nen:begin (generated by install.sh — do not edit inside the markers) -->
## nen skills

Six engineering disciplines, one per Nen category (https://github.com/rlaope/nen).
When a task matches a description below, read that skill's SKILL.md file FIRST
and follow its Method before acting. Do not paraphrase from this list alone.

EOF
  for s in $SKILLS; do
    printf -- '- **%s** (%s/skills/%s/SKILL.md): %s\n' "$s" "$NEN_HOME" "$s" "$(skill_description "$s")"
  done
  cat <<'EOF'

If a skill fires on the wrong problem, its Boundaries section names the sibling
skill to hand off to — follow the hand-off.
<!-- nen:end -->
EOF
}

append_block() {
  # idempotent: replace any existing nen block in $1, else append
  file="$1"
  mkdir -p "$(dirname "$file")"
  touch "$file"
  tmp="$(mktemp)"
  awk '/<!-- nen:begin/{skip=1} !skip{print} /<!-- nen:end/{skip=0}' "$file" >"$tmp"
  { cat "$tmp"; [ -s "$tmp" ] && echo ""; routing_block; } >"$file"
  rm -f "$tmp"
  say "Routing block written to $file"
}

install_claude() {
  dest="$HOME/.claude/skills/nen"
  mkdir -p "$dest"
  cp -R "$SRC/skills" "$dest/"
  cp -R "$SRC/.claude-plugin" "$dest/" 2>/dev/null || true
  say "Claude Code: installed to $dest (invoke as /nen:<skill>)"
  say "  (or use the plugin: /plugin marketplace add rlaope/nen)"
}

install_cursor() {
  mkdir -p .cursor/rules
  for s in $SKILLS; do
    body_file="$NEN_HOME/skills/$s/SKILL.md"
    desc="$(skill_description "$s")"
    {
      printf -- '---\ndescription: "%s"\nalwaysApply: false\n---\n\n' "$(printf '%s' "$desc" | sed 's/"/\\"/g')"
      awk 'NR==1 && /^---$/ {infm=1; next} infm && /^---$/ {infm=0; next} !infm {print}' "$body_file"
    } >".cursor/rules/nen-$s.mdc"
  done
  say "Cursor: wrote .cursor/rules/nen-<skill>.mdc (6 rules, agent-requested by description)"
}

do_target() {
  case "$1" in
    claude) install_claude ;;
    cursor) install_cursor ;;
    copilot) append_block "${DEST:-.github/copilot-instructions.md}" ;;
    codex) append_block "${DEST:-$HOME/.codex/AGENTS.md}" ;;
    opencode) append_block "${DEST:-$HOME/.config/opencode/AGENTS.md}" ;;
    gemini) append_block "${DEST:-$HOME/.gemini/GEMINI.md}" ;;
    qwen) append_block "${DEST:-$HOME/.qwen/QWEN.md}" ;;
    kimi|antigravity|pi|agents-md) append_block "${DEST:-./AGENTS.md}" ;;
    *) echo "unknown agent: $1" >&2; usage; exit 1 ;;
  esac
}

fetch_repo
install_home

if [ "$AGENT" = "auto" ]; then
  found=""
  [ -d "$HOME/.claude" ] && { do_target claude; found=1; }
  [ -d "$HOME/.codex" ] && { do_target codex; found=1; }
  [ -d "$HOME/.config/opencode" ] && { do_target opencode; found=1; }
  [ -d "$HOME/.gemini" ] && { do_target gemini; found=1; }
  [ -d "$HOME/.qwen" ] && { do_target qwen; found=1; }
  [ -d ".cursor" ] && { do_target cursor; found=1; }
  if [ -z "$found" ]; then
    say "No known agent detected — writing the generic block to ./AGENTS.md"
    do_target agents-md
  fi
else
  do_target "$AGENT"
fi

say ""
say "nen installed. Six skills: $SKILLS"
say "Uninstall: remove $NEN_HOME, the block between <!-- nen:begin/end --> markers,"
say "           ~/.claude/skills/nen, and .cursor/rules/nen-*.mdc as applicable."
