#!/usr/bin/env python3
"""Generate per-agent adapter artifacts from skills/ — the single source of truth.

Outputs:
  AGENTS.md            routing file for the AGENTS.md family (Codex, OpenCode,
                       Antigravity, Kimi, Qwen, OpenClaw, ...), repo-relative paths
  .cursor/rules/*.mdc  one Cursor rule per skill

Usage: python3 scripts/gen-adapters.py [--check]
--check verifies the committed artifacts match what skills/ would generate
(exit 1 on drift) without writing anything. CI runs this on every push.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SKILLS = ["enhancer", "transmuter", "emitter", "specialist", "conjurer", "manipulator", "hatsu", "en", "vow"]


def parse(s):
    text = (ROOT / "skills" / s / "SKILL.md").read_text(encoding="utf-8")
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.S)
    fm, body = m.groups()
    desc = re.search(r"^description:\s*(.+)$", fm, re.M).group(1)
    return desc, body.strip() + "\n"


def agents_md():
    lines = [
        "<!-- generated by scripts/gen-adapters.py — edit skills/*/SKILL.md instead -->",
        "# nen skills — the En protocol",
        "",
        "The nen abilities (https://github.com/rlaope/nen): one per Nen category, hatsu",
        "(forging new skills) at the center, en — this protocol itself — and vow,",
        "the pre-commitments that bind each engagement.",
        "",
        "Run En on every incoming task:",
        "1. Classify the WORK, not the words. Ask what must be true afterward — a number",
        "   moved (enhancer), a behavior-preserving change of shape (transmuter), words",
        "   that land with an audience (emitter), a mechanism named (specialist),",
        "   survival under failure (conjurer), verified distributed work (manipulator),",
        "   an ability that doesn't exist yet (hatsu). Never route on keyword overlap;",
        "   the descriptions below are scent, not the mechanism.",
        "2. Engage every skill the work genuinely spans — stacking two or three in",
        "   dependency order is normal. Read each engaged SKILL.md FIRST, then act.",
        '3. Announce the engagement in one line, e.g. "En: specialist -> conjurer".',
        "4. Right under the announcement, declare the engagement's vows — up to three",
        "   falsifiable pledges distilled from the engaged skills' Done means plus up to",
        "   three scope pledges — and audit every vow before claiming done",
        "   (skills/vow/SKILL.md).",
        '5. "nen off" suspends this protocol; "nen on" resumes it. Acknowledge both.',
        "6. If a skill still fires on the wrong problem, its Boundaries section names",
        "   the sibling to hand off to — follow the hand-off.",
        "",
    ]
    for s in SKILLS:
        desc, _ = parse(s)
        lines.append(f"- **{s}** (skills/{s}/SKILL.md): {desc}")
    lines.append("")
    return "\n".join(lines)


def mdc(s):
    desc, body = parse(s)
    escaped = desc.replace('"', '\\"')
    return f'---\ndescription: "{escaped}"\nalwaysApply: false\n---\n\n{body}'


def targets():
    out = {ROOT / "AGENTS.md": agents_md()}
    for s in SKILLS:
        out[ROOT / ".cursor" / "rules" / f"nen-{s}.mdc"] = mdc(s)
    return out


check = "--check" in sys.argv
drift = []
for path, content in targets().items():
    rel = path.relative_to(ROOT)
    if check:
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            drift.append(str(rel))
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {rel}")

if check:
    if drift:
        print("DRIFT — regenerate with scripts/gen-adapters.py:", ", ".join(drift))
        sys.exit(1)
    print("adapters in sync")
